version: '3.8'

services:
  mysql_service_1:
    image: mysql:8.0
    container_name: auth_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
    ports:
      - "3307:3306"
    volumes:
      - mysql_auth_service_data:/var/lib/mysql

  mysql_service_2:
    image: mysql:8.0
    container_name: history_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db2
      MYSQL_USER: user2
      MYSQL_PASSWORD: pass2
    ports:
      - "3308:3306"
    volumes:
      - mysql_history_service_data:/var/lib/mysql

volumes:
  mysql_auth_service_data:
  mysql_history_service_data:
